---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: node
    dns_sd_configs:
      - names:
          - tasks.node-exporter
        type: "A"
        port: 9100
  - job_name: postgres
    static_configs:
      - targets:
          - postgres-exporter:9187

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager-1:9093
            - alertmanager-2:9093
