{
 "title": "Postgres",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_name", "label": "Swarm Node", "query": "node_meta" }
  ]
 },
 "panels": [
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Replication Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "pg_replication_state" }
   ]
  },
  {
   "title": "Replication Status History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_replication_state", "legendFormat": "Up" },
    { "expr": "1 - pg_replication_state", "legendFormat": "Down" }
   ]
  },
  {
   "title": "Replication Lag in Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_replication_pg_wal_lsn_diff)",
     "legendFormat": "All Replication Slots"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk Usage on /var",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{mountpoint='/var'} / node_filesystem_size_bytes{mountpoint='/var'}) * on(instance) group_left(node_name) node_meta{node_name=\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(node_name) node_meta{node_name=\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}