version: "3.7"

# Default logging
x-logging: &default-logging
  driver: json-file
  options:
    max-file: "3"
    max-size: "10m"

services:
  app:
    image: example/example1/example-rails/example:${example_IMAGE_TAG}
    deploy:
      placement:
        constraints:
          - node.labels.example == true
      replicas: ${example_REPLICAS}
      resources:
        limits:
          memory: 10g
      update_config:
        parallelism: 1
    environment:
      MAILER_DEFAULT_FROM:
      MAILER_DOMAIN:
      MAILER_HOST:
      PASSENGER_APP_ENV: ${RAILS_ENV}
      RAILS_ENV:

      SAML_EMAIL_ATTRIBUTE:
      SAML_FIRST_NAME_ATTRIBUTE:
      SAML_LAST_NAME_ATTRIBUTE:
      SAML_LOGOUT_URL:

      ALMA_API_KEY:

      SPRINGSHARE_LIBCAL_ID:
      SPRINGSHARE_LIBCAL_SECRET:
      SPRINGSHARE_LIBCAL_GRANTTYPE:

      BORROWDIRECT_RESHARE_DB:
      BORROWDIRECT_RESHARE_HOST:
      BORROWDIRECT_RESHARE_PORT:
      BORROWDIRECT_RESHARE_PWD:
      BORROWDIRECT_RESHARE_UID:

      COLUMBIA_ILLIAD_MSSQL_DB:
      COLUMBIA_ILLIAD_MSSQL_HOST:
      COLUMBIA_ILLIAD_MSSQL_PORT:
      COLUMBIA_ILLIAD_MSSQL_PWD:
      COLUMBIA_ILLIAD_MSSQL_UID:

      CORNELL_ILLIAD_MSSQL_DB:
      CORNELL_ILLIAD_MSSQL_HOST:
      CORNELL_ILLIAD_MSSQL_PORT:
      CORNELL_ILLIAD_MSSQL_PWD:
      CORNELL_ILLIAD_MSSQL_UID:

      DARTMOUTH_ILLIAD_MSSQL_DB:
      DARTMOUTH_ILLIAD_MSSQL_HOST:
      DARTMOUTH_ILLIAD_MSSQL_PORT:
      DARTMOUTH_ILLIAD_MSSQL_PWD:
      DARTMOUTH_ILLIAD_MSSQL_UID:

      DUKE_ILLIAD_MSSQL_DB:
      DUKE_ILLIAD_MSSQL_HOST:
      DUKE_ILLIAD_MSSQL_PORT:
      DUKE_ILLIAD_MSSQL_PWD:
      DUKE_ILLIAD_MSSQL_UID:

      HARVARD_ILLIAD_MSSQL_DB:
      HARVARD_ILLIAD_MSSQL_HOST:
      HARVARD_ILLIAD_MSSQL_PORT:
      HARVARD_ILLIAD_MSSQL_PWD:
      HARVARD_ILLIAD_MSSQL_UID:

      MIT_ILLIAD_MSSQL_DB:
      MIT_ILLIAD_MSSQL_HOST:
      MIT_ILLIAD_MSSQL_PORT:
      MIT_ILLIAD_MSSQL_PWD:
      MIT_ILLIAD_MSSQL_UID:

      PRINCETON_ILLIAD_MSSQL_DB:
      PRINCETON_ILLIAD_MSSQL_HOST:
      PRINCETON_ILLIAD_MSSQL_PORT:
      PRINCETON_ILLIAD_MSSQL_PWD:
      PRINCETON_ILLIAD_MSSQL_UID:

      RESHARE_DB:
      RESHARE_HOST:
      RESHARE_PORT:
      RESHARE_PWD:
      RESHARE_UID:

      example_BORROWDIRECT_MSSQL_DB:
      example_BORROWDIRECT_MSSQL_HOST:
      example_BORROWDIRECT_MSSQL_PORT:
      example_BORROWDIRECT_MSSQL_PWD:
      example_BORROWDIRECT_MSSQL_UID:

      example_EZBORROW_MSSQL_DB:
      example_EZBORROW_MSSQL_HOST:
      example_EZBORROW_MSSQL_PORT:
      example_EZBORROW_MSSQL_PWD:
      example_EZBORROW_MSSQL_UID:

      example_GATECOUNT_SFTP_HOST:
      example_GATECOUNT_SFTP_PWD:
      example_GATECOUNT_SFTP_USER:

      example_ILLIAD_MSSQL_DB:
      example_ILLIAD_MSSQL_HOST:
      example_ILLIAD_MSSQL_PORT:
      example_ILLIAD_MSSQL_PWD:
      example_ILLIAD_MSSQL_UID:

      YALE_ILLIAD_MSSQL_DB:
      YALE_ILLIAD_MSSQL_HOST:
      YALE_ILLIAD_MSSQL_PORT:
      YALE_ILLIAD_MSSQL_PWD:
      YALE_ILLIAD_MSSQL_UID:

    healthcheck:
      test: ["CMD", "/home/app/webapp/healthcheck.rb"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 1m30s
    logging: *default-logging
    networks:
      - app
      - database
      - shibboleth
    secrets:
      - source: example_rails_database_config
        target: /home/app/webapp/config/database.yml
        uid: "${APP_USER_UID}"
        gid: "${APP_USER_GID}"
        mode: 0440
      - source: example_rails_secrets_config
        target: /home/app/webapp/config/secrets.yml
        uid: "${APP_USER_UID}"
        gid: "${APP_USER_GID}"
        mode: 0440
    volumes:
      - ezpaarse_output:/tmp/example_ezproxy
      - gate_count:/tmp/gate_count
      - example_tmp_data_dist:/home/app/webapp/tmp
  delayed_jobs:
    image: example/example1/example-rails/example:${example_IMAGE_TAG}
    command: bash -c "/sbin/my_init --skip-startup-files --skip-runit -- /sbin/setuser app bundle exec rails jobs:work"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.delayed-jobs == true
    environment:
      MAILER_DEFAULT_FROM:
      MAILER_DOMAIN:
      MAILER_HOST:
      PASSENGER_APP_ENV: ${RAILS_ENV}
      RAILS_ENV:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "ps aux | grep -m 1 -c 'bundle exec rails jobs:work' || exit 1",
        ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 2m
    logging: *default-logging
    networks:
      - app
      - database
    secrets:
      - source: example_rails_database_config
        target: /home/app/webapp/config/database.yml
        uid: "${APP_USER_UID}"
        gid: "${APP_USER_GID}"
        mode: 0440
      - source: example_rails_secrets_config
        target: /home/app/webapp/config/secrets.yml
        uid: "${APP_USER_UID}"
        gid: "${APP_USER_GID}"
        mode: 0440
    volumes:
      - example_tmp_data_dist:/home/app/webapp/tmp
    working_dir: /home/app/webapp

networks:
  app:
    driver: overlay
  database:
    external: true
  shibboleth:
    external: true

secrets:
  example_rails_database_config:
    external: true
    name: example_rails_database_config_${RAILS_DATABASE_CONFIG_VERSION}
  example_rails_secrets_config:
    external: true
    name: example_rails_secrets_config_${RAILS_SECRETS_CONFIG_VERSION}

volumes:
  ezpaarse_output:
    external: true
  gate_count:
    external: true
  example_tmp_data_dist:
    external: true
