version: "3.7"

services:
  python_jobs:
    image: example/example1/example-python-jobs/example_python_jobs:${PYTHON_JOBS_IMAGE_TAG}
    deploy:
      placement:
        constraints:
          - node.labels.example == true
      replicas: ${PYTHON_JOBS_REPLICAS}
      update_config:
        parallelism: 1
    environment:
      RAILS_ENV:
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[t]ail' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - database
    secrets:
      - source: example_python_jobs_database_secret
        target: /home/app/config/example.ini
        uid: "${APP_USER_UID}"
        gid: "${APP_USER_GID}"
        mode: 0440
      - source: example_python_jobs_libwizard_secret
        target: /home/app/config/libwizard.ini
        uid: "${APP_USER_UID}"
        gid: "${APP_USER_GID}"
        mode: 0440
    volumes:
      - gate_count:/gate_count
    working_dir: /home/app

networks:
  database:
    external: true

secrets:
  example_python_jobs_database_secret:
    external: true
    name: example_python_jobs_database_secret_${PYTHON_JOBS_DATABASE_SECRET_VERSION}
  example_python_jobs_libwizard_secret:
    external: true
    name: example_python_jobs_libwizard_secret_${PYTHON_JOBS_LIBWIZARD_SECRET_VERSION}

volumes:
  gate_count:
    external: true
