---

# Variables setup
- name: Include os-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# The vmware network interface drops outbound packets due to bad checksums. This causes networking issues
# on the docker swarm overlay network/s. Disable checksum offloading for primary interface.
- name: Disable checksum offloading for this session
  ansible.builtin.command: "ethtool -K {{ ansible_default_ipv4.interface }} tx off"

- name: Check if NetworkManager folder exists
  stat:
    path: "/etc/NetworkManager/dispatcher.d"
  register: network_manager_folder

- name: Disable checksum offloading on boot
  ansible.builtin.template:
    src: disable-checksum-offload.sh.j2
    dest: /etc/NetworkManager/dispatcher.d/disable-checksum-offload.sh
    owner: root
    group: root
    mode: '0744'
  when: network_manager_folder.stat.exists

# Makes sure that the repo cache is fresh
- name: Update APT cache.
  apt:
    update_cache: true
  when: ansible_os_family == 'Debian'
  changed_when: false

# Install python-pip
- include_tasks: setup-python-pip.yml

# Install the Docker repository
- include_tasks: "repo-{{ ansible_os_family }}.yml"
  when: not skip_repo

# Install the Docker dependencies
- name: Install Docker dependencies.
  package:
    name: "{{ docker_dependencies }}"
    state: present
  when: not skip_containerd or not skip_engine

# Install containerd
- include_tasks: setup-containerd.yml
  when: not skip_containerd

# Install the Docker Engine
- include_tasks: setup-docker-engine.yml
  when: not skip_engine

# Install the Docker CLI
- include_tasks: setup-docker-cli.yml
  when: not skip_cli

# Setup the Docker Swarm Cluster
- block:
    - include_tasks: setup-swarm-cluster.yml
    - include_tasks: setup-swarm-labels.yml
  when: not skip_swarm

# Adds the Docker admin users to the Docker group
- include_tasks: setup-docker-group.yml
  when: not skip_group

# Install docker-py
- include_tasks: setup-docker-py.yml
  when: not skip_docker_py

# Install docker-compose
- include_tasks: setup-docker-compose.yml
  when: not skip_docker_compose
